name: Docker build

on:
   #Trigger the workflow on pull or pull request,
   #but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Docker build
    name: Run Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
      
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      
      - name: Build
        run: |
          docker build . 
